<a href="https://colab.research.google.com/github/hn5003162/Analise_Exploratoria_de_Dados/blob/main/Projeto_Aplicado_I_AED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
# decimal = "," informa que o , é o separador de decimais
base = pd.read_csv("https://raw.githubusercontent.com/hn5003162/Mack_Projeto_Aplicado_I/main/base-projeto-aplicado-i.csv",sep="|",decimal = ",")
base.head(50)

,ano,sigla_uf,nome_uf,nome_regiao,produto,area_plantada,area_colhida,quantidade_produzida,perdas,valor_producao,...,area_cafe,producao_cafe,valor_total_producao_cafe,despesa_total_comparacao,despesa_total,despesa_defensivos,quantidade_tratores,quantidade_maquina_colheita,quantidade_maquinas_plantio,proporcao_despesa_defensivos
0,2010,AC,Acre,Norte,Café,1271.0,1003.0,1029.0,279.847,2777.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010,AL,Alagoas,Nordeste,Café,5.0,5.0,2.0,0.000,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010,AM,Amazonas,Norte,Café,2432.0,2048.0,3902.0,758.988,8804.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,AP,Amapá,Norte,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,BA,Bahia,Nordeste,Café,152056.0,152056.0,153262.0,0.000,560050.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2010,CE,Ceará,Nordeste,Café,7432.0,7432.0,3224.0,0.000,12025.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2010,DF,Distrito Federal,Centro-oeste,Café,1000.0,935.0,1052.0,73.000,3156.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2010,ES,Espírito Santo,Sudeste,Café,473183.0,473183.0,616722.0,0.000,1812702.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2010,GO,Goiás,Centro-oeste,Café,10026.0,10026.0,22835.0,0.000,73756.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2010,MA,Maranhão,Nordeste,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2010,MG,Minas Gerais,Sudeste,Café,1026613.0,1026613.0,1504188.0,0.000,6980674.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2010,MS,Mato Grosso do Sul,Centro-oeste,Café,1253.0,1253.0,1502.0,0.000,5695.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2010,MT,Mato Grosso,Centro-oeste,Café,15186.0,15186.0,12182.0,0.000,27101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2010,PA,Pará,Norte,Café,11201.0,11201.0,11951.0,0.000,37162.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2010,PB,Paraíba,Nordeste,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010,PE,Pernambuco,Nordeste,Café,3873.0,3873.0,1924.0,0.000,6687.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2010,PI,Piauí,Nordeste,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2010,PR,Paraná,Sul,Café,82673.0,82673.0,139054.0,0.000,571777.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2010,RJ,Rio de Janeiro,Sudeste,Café,12940.0,12940.0,15012.0,0.000,53012.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2010,RN,Rio Grande do Norte,Nordeste,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2010,RO,Rondônia,Norte,Café,156606.0,156606.0,141160.0,0.000,317392.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2010,RR,Roraima,Norte,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2010,RS,Rio Grande do Sul,Sul,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2010,SC,Santa Catarina,Sul,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2010,SE,Sergipe,Nordeste,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2010,SP,São Paulo,Sudeste,Café,204074.0,202752.0,278264.0,1109.897,1107604.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2010,TO,Tocantins,Norte,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2011,AC,Acre,Norte,Café,1194.0,1194.0,1374.0,0.000,4515.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2011,AL,Alagoas,Nordeste,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2011,AM,Amazonas,Norte,Café,1940.0,1716.0,2543.0,286.001,5773.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2011,AP,Amapá,Norte,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2011,BA,Bahia,Nordeste,Café,153804.0,153804.0,151742.0,0.000,838352.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2011,CE,Ceará,Nordeste,Café,7474.0,7474.0,3429.0,0.106,13037.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,2011,DF,Distrito Federal,Centro-oeste,Café,780.0,780.0,1148.0,0.160,5530.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2011,ES,Espírito Santo,Sudeste,Café,467181.0,467181.0,709596.0,0.000,3043039.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2011,GO,Goiás,Centro-oeste,Café,8863.0,8863.0,19411.0,0.000,71424.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2011,MA,Maranhão,Nordeste,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2011,MG,Minas Gerais,Sudeste,Café,1025366.0,1025366.0,1335738.0,0.000,9935604.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2011,MS,Mato Grosso do Sul,Centro-oeste,Café,1314.0,1314.0,1562.0,0.000,7922.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2011,MT,Mato Grosso,Centro-oeste,Café,19884.0,19884.0,8269.0,0.122,26155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2011,PA,Pará,Norte,Café,10490.0,10490.0,10251.0,0.347,40171.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2011,PB,Paraíba,Nordeste,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2011,PE,Pernambuco,Nordeste,Café,5092.0,5092.0,2460.0,0.120,8555.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2011,PI,Piauí,Nordeste,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2011,PR,Paraná,Sul,Café,74854.0,74854.0,110728.0,1.672,773012.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,2011,RJ,Rio de Janeiro,Sudeste,Café,12864.0,12864.0,15600.0,0.000,81185.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2011,RN,Rio Grande do Norte,Nordeste,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,2011,RO,Rondônia,Norte,Café,153516.0,153516.0,88119.0,0.000,258948.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,2011,RR,Roraima,Norte,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,2011,RS,Rio Grande do Sul,Sul,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Exploração de estrutura de dados: colunas

In [96]:
#Número de linhas e colunas da base
base.shape

(216, 23)

In [97]:
# Estrutura do datase
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 23 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ano                               216 non-null    int64
 1   sigla_uf                          216 non-null    object
 2   nome_uf                           216 non-null    object
 3   nome_regiao                       216 non-null    object
 4   produto                           216 non-null    object
 5   area_plantada                     129 non-null    float64
 6   area_colhida                      129 non-null    float64
 7   quantidade_produzida              129 non-null    float64
 8   perdas                            129 non-null    float64
 9   valor_producao                    129 non-null    float64
 10  emissao                           216 non-null    float64
 11  area_nao_utilizada                27 non-null     float64
 12  quantidade_estabelecimentos_cafe  27 non-null     float64
 13  area_cafe                         27 non-null     float64
 14  producao_cafe                     27 non-null     float64
 15  valor_total_producao_cafe         27 non-null     float64
 16  despesa_total_comparacao          27 non-null     float64
 17  despesa_total                     27 non-null     float64
 18  despesa_defensivos                27 non-null     float64
 19  quantidade_tratores               27 non-null     float64
 20  quantidade_maquina_colheita       27 non-null     float64
 21  quantidade_maquinas_plantio       27 non-null     float64
 22  proporcao_despesa_defensivos      27 non-null     float64
dtypes: float64(18), int64(1), object(4)
memory usage: 38.9+ KB

In [98]:
# Valores das colunas
base.describe(include='all')

,ano,sigla_uf,nome_uf,nome_regiao,produto,area_plantada,area_colhida,quantidade_produzida,perdas,valor_producao,...,area_cafe,producao_cafe,valor_total_producao_cafe,despesa_total_comparacao,despesa_total,despesa_defensivos,quantidade_tratores,quantidade_maquina_colheita,quantidade_maquinas_plantio,proporcao_despesa_defensivos
count,216.00000,216,216,216,216,1.290000e+02,1.290000e+02,1.290000e+02,129.000000,1.290000e+02,...,27.000000,2.700000e+01,2.700000e+01,2.700000e+01,2.700000e+01,27.000000,2.700000e+01,2.700000e+01,2.700000e+01,27.000000
unique,NaN,27,27,5,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,AC,Acre,Nordeste,Café,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,8,8,72,216,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2013.50000,NaN,NaN,NaN,NaN,1.265915e+05,1.262692e+05,1.765149e+05,328.541264,9.987940e+05,...,46251.148148,6.761174e+04,5.320704e+05,1.190120e+06,1.701248e+06,151573.481481,1.702416e+07,5.828436e+06,4.075691e+06,0.136222
std,2.29661,NaN,NaN,NaN,NaN,2.563047e+05,2.561992e+05,3.834141e+05,1159.013713,2.433704e+06,...,174508.631602,2.661681e+05,1.968547e+06,1.750389e+06,2.354958e+06,155577.287171,2.089218e+07,6.276819e+06,4.672099e+06,0.084676
min,2010.00000,NaN,NaN,NaN,NaN,5.000000e+00,5.000000e+00,2.000000e+00,0.000000,1.000000e+00,...,0.000000,0.000000e+00,0.000000e+00,4.971000e+03,5.438300e+04,3206.000000,3.527460e+05,9.003300e+04,6.421900e+04,0.036000
25%,2011.75000,NaN,NaN,NaN,NaN,1.648000e+03,1.538000e+03,1.534000e+03,0.000000,6.687000e+03,...,0.000000,0.000000e+00,2.835000e+03,4.696500e+04,4.743115e+05,50729.500000,2.371060e+06,1.164270e+06,6.891330e+05,0.065000
50%,2013.50000,NaN,NaN,NaN,NaN,1.120100e+04,1.120100e+04,1.218200e+04,0.399000,4.017100e+04,...,144.000000,6.500000e+01,1.702600e+04,2.878030e+05,6.798150e+05,100601.000000,6.544964e+06,2.830683e+06,1.296181e+06,0.109000
75%,2015.25000,NaN,NaN,NaN,NaN,1.520560e+05,1.520560e+05,1.408360e+05,81.667000,6.946090e+05,...,2758.500000,3.766000e+03,1.520090e+05,1.990214e+06,2.140766e+06,200419.000000,2.395181e+07,9.269072e+06,6.730812e+06,0.191500
max,2017.00000,NaN,NaN,NaN,NaN,1.041541e+06,1.041540e+06,1.834171e+06,7307.301000,1.402012e+07,...,903032.000000,1.380573e+06,1.024950e+07,6.268032e+06,1.097884e+07,673111.000000,5.971232e+07,2.344271e+07,1.824127e+07,0.312000

In [29]:
# Como fazer para selecionar apenas uma coluna
#base["ano"]
#base[["ano","nome_uf"]]
#base["valor_producao"]

Operações:

In [100]:
# Desvio padrão da emissao de gases
base.emissao.std()

150908.82091298318

In [102]:
#Frequencia de valores // não tem utilidade
#base.ano.value_counts()

In [34]:
# seleciona várias colunas. Colocar lista de campos
#base[["ano","nome_uf","emissao"]]

In [ ]:
# 3) Qual é a região com maior perda de alimentos?
# mudar forma de cálculo usando groupby() // 22/09/2023 Hideki

#Cria um datafame somente das perdar por região. Elimina as regiões que não tem dados (NA)
base_perda = base[["nome_regiao","area_plantada","perdas"]]
# Elimina todos os registro que tenham NA no campo perdas
base_perda = base_perda.dropna(subset=['perdas'])

#Area plantada em números absolutos de 2010 a 2017"
print()
print("Area plantada:")
print("Norte       : ",base_perda[base_perda.nome_regiao == "Norte"].area_plantada.sum())
print("Nordeste    : ",base_perda[base_perda.nome_regiao == "Nordeste"].area_plantada.sum())
print("Centro-oeste: ",base_perda[base_perda.nome_regiao == "Centro-oeste"].area_plantada.sum())
print("Sudeste     : ",base_perda[base_perda.nome_regiao == "Sudeste"].area_plantada.sum())
print("Sul         : ",base_perda[base_perda.nome_regiao == "Sul"].area_plantada.sum())



#Perdas em números absolutos:
print()
print("Perdas de 2010 a 2017:")
print("Norte       :",base_perda[base_perda.nome_regiao == "Norte"].perdas.sum())
print("Nordeste    :",base_perda[base_perda.nome_regiao == "Nordeste"].perdas.sum())
print("Centro-oeste:",base_perda[base_perda.nome_regiao == "Centro-oeste"].perdas.sum())
print("Sudeste     :",base_perda[base_perda.nome_regiao == "Sudeste"].perdas.sum())
print("Sul         :",base_perda[base_perda.nome_regiao == "Sul"].perdas.sum())

#Perdas proporcionais à area plantada
print()
print("Perdas proporcionais à area plantada de 2010 a 2017:")
print("Norte       : ","{0:.5f}".format(base_perda[base_perda.nome_regiao == "Norte"].perdas.sum() / base_perda[base_perda.nome_regiao == "Norte"].area_plantada.sum()))
print("Nordeste    : ","{0:.5f}".format(base_perda[base_perda.nome_regiao == "Nordeste"].perdas.sum() / base_perda[base_perda.nome_regiao == "Nordeste"].area_plantada.sum()))
print("Centro-oeste: ","{0:.5f}".format(base_perda[base_perda.nome_regiao == "Centro-oeste"].perdas.sum() / base_perda[base_perda.nome_regiao == "Centro-oeste"].area_plantada.sum()))
print("Sudeste     : ","{0:.5f}".format(base_perda[base_perda.nome_regiao == "Sudeste"].perdas.sum() / base_perda[base_perda.nome_regiao == "Sudeste"].area_plantada.sum()))
print("Sul         : ","{0:.5f}".format(base_perda[base_perda.nome_regiao == "Sul"].perdas.sum() / base_perda[base_perda.nome_regiao == "Sul"].area_plantada.sum()))

Area plantada:
Norte       :  924910.0
Nordeste    :  1318472.0
Centro-oeste:  221474.0
Sudeste     :  13403920.0
Sul         :  461527.0

Perdas:
Norte       : 14665.339
Nordeste    : 11285.072
Centro-oeste: 582.188
Sudeste     : 12620.574
Sul         : 3228.65

Perdas proporcionais à area plantada:
Norte       :  0.01586
Nordeste    :  0.00856
Centro-oeste:  0.00263
Sudeste     :  0.00094
Sul         :  0.00700

In [ ]:
# 1) Qual é a relação entre o plantio e a emissão de gases de efeito estufa?
base_plantada_emissao = base[["area_plantada","emissao"]]
#Retira todo e qualquer registro com NA, seja da area plantada ou na emissao"
base_plantada_emissao = base_plantada_emissao.dropna()
print("Emissão de gases por hectare:",base_plantada_emissao.emissao.sum()/base_plantada_emissao.area_plantada.sum())

Emissão de gases por hectare: 0.32411400511062166

2) Qual é a perda de cada região por ano?

In [90]:
# Versão Hideki usando o campo perdas do dataframe


base_perda_regiao = base[["ano","nome_regiao","perdas"]]
base_perda_regiao.dropna()


base_perda_regiao = base_perda_regiao.groupby(['ano', 'nome_regiao'])

base_perda_regiao = base_perda_regiao.sum()


display(base_perda_regiao)

                     perdas
ano  nome_regiao
2010 Centro-oeste    73.000
     Nordeste         0.000
     Norte         1038.835
     Sudeste       1109.897
     Sul              0.000
2011 Centro-oeste     0.282
     Nordeste         0.226
     Norte          286.348
     Sudeste          3.423
     Sul              1.672
2012 Centro-oeste     0.274
     Nordeste       163.723
     Norte          510.815
     Sudeste       1010.505
     Sul           1212.627
2013 Centro-oeste    35.055
     Nordeste        32.727
     Norte         4797.614
     Sudeste        791.382
     Sul            110.429
2014 Centro-oeste     5.466
     Nordeste      1062.496
     Norte          229.711
     Sudeste        598.136
     Sul           1460.454
2015 Centro-oeste   321.130
     Nordeste      7121.073
     Norte          225.188
     Sudeste       7222.347
     Sul            309.733
2016 Centro-oeste   146.357
     Nordeste       842.320
     Norte         7336.020
     Sudeste       1590.948
     Sul             76.683
2017 Centro-oeste     0.624
     Nordeste      2062.507
     Norte          240.808
     Sudeste        293.936
     Sul             57.052

In [94]:
# Agrupado por região e ano

base_perda_regiao = base[["ano","nome_regiao","perdas"]]
base_perda_regiao.dropna()

base_perda_regiao = base_perda_regiao.groupby(['nome_regiao','ano'])
base_perda_regiao = base_perda_regiao.sum()

display(base_perda_regiao)

#Perdas totais por ano
base_perda_regiao = base[["ano","nome_regiao","perdas"]]
base_perda_regiao.dropna()

base_perda_regiao = base_perda_regiao.groupby(['ano'])
base_perda_regiao = base_perda_regiao.sum()

display(base_perda_regiao)

                     perdas
nome_regiao  ano
Centro-oeste 2010    73.000
             2011     0.282
             2012     0.274
             2013    35.055
             2014     5.466
             2015   321.130
             2016   146.357
             2017     0.624
Nordeste     2010     0.000
             2011     0.226
             2012   163.723
             2013    32.727
             2014  1062.496
             2015  7121.073
             2016   842.320
             2017  2062.507
Norte        2010  1038.835
             2011   286.348
             2012   510.815
             2013  4797.614
             2014   229.711
             2015   225.188
             2016  7336.020
             2017   240.808
Sudeste      2010  1109.897
             2011     3.423
             2012  1010.505
             2013   791.382
             2014   598.136
             2015  7222.347
             2016  1590.948
             2017   293.936
Sul          2010     0.000
             2011     1.672
             2012  1212.627
             2013   110.429
             2014  1460.454
             2015   309.733
             2016    76.683
             2017    57.052

<ipython-input-94-bcc8bd087c3f>:15: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  base_perda_regiao = base_perda_regiao.sum()

         perdas
ano
2010   2221.732
2011    291.951
2012   2897.944
2013   5767.207
2014   3356.263
2015  15199.471
2016   9992.328
2017   2654.927

In [110]:
# Qual é a relação de perdas e emissão?

# 1) Qual é a relação entre o plantio e a emissão de gases de efeito estufa?
base_perdas_emissao = base[["nome_regiao","ano","area_plantada","perdas","emissao"]]
#Retira todo e qualquer registro com NA, seja da area plantada ou na emissao"
base_perdas_emissao.dropna()

base_perdas_emissao = base_perdas_emissao.groupby(['nome_regiao','ano'])
base_perdas_emissao = base_perdas_emissao.sum()

display(base_perdas_emissao)

                   area_plantada    perdas      emissao
nome_regiao  ano
Centro-oeste 2010        27465.0    73.000   190981.313
             2011        30841.0     0.282   237783.155
             2012        31517.0     0.274   245794.916
             2013        28790.0    35.055   209243.539
             2014        27386.0     5.466   228969.004
             2015        28812.0   321.130   219638.838
             2016        24259.0   146.357   207676.099
             2017        22404.0     0.624   227224.503
Nordeste     2010       163366.0     0.000   287474.726
             2011       166370.0     0.226   311106.299
             2012       169260.0   163.723   296987.037
             2013       170690.0    32.727   286390.545
             2014       170957.0  1062.496   297580.760
             2015       173955.0  7121.073   299908.499
             2016       172040.0   842.320   287599.747
             2017       131834.0  2062.507   289680.303
Norte        2010       171510.0  1038.835    14283.199
             2011       167140.0   286.348    14154.001
             2012       138064.0   510.815    14999.851
             2013       107926.0  4797.614    15359.413
             2014        92310.0   229.711    15284.309
             2015        84056.0   225.188    15367.939
             2016        89774.0  7336.020    15149.345
             2017        74130.0   240.808    15057.627
Sudeste      2010      1716810.0  1109.897    94255.340
             2011      1709794.0     3.423   101137.576
             2012      1711332.0  1010.505   103940.732
             2013      1721887.0   791.382   106242.297
             2014      1673165.0   598.136   112129.905
             2015      1654702.0  7222.347   119766.073
             2016      1679099.0  1590.948   122167.574
             2017      1537131.0   293.936   123961.384
Sul          2010        82673.0     0.000  1064857.451
             2011        74854.0     1.672  1063188.210
             2012        72400.0  1212.627  1045301.824
             2013        64964.0   110.429  1072395.094
             2014        38333.0  1460.454  1077459.496
             2015        44747.0   309.733  1066430.963
             2016        43388.0    76.683  1097022.100
             2017        40168.0    57.052  1058251.658